### ISSUE TITLE
[Task] Checklist before deploying v0.4.0

### ISSUE THREAD

**Issue by No767** [No767/Kumiko#159]
### Targeted Release Date: Nov 26, 2022

Here's a list of stuff that needs to be done before Kumiko v0.4.0 goes live. This list will be changed and new ones will get added later on

- [x] Audit all economy commands
- [x] Audit all additional commands (not from Rin)
- [x] Globally roll out all slash commands
- [x] #158
- [x] #157
- [x] Update Docs
- [x] Fix unbanning user issue
- [x] Add a global error handler for no permissions
- [x] #160
- [x] Rely on user perms and roles instead of bot perms for admin cmds
- [x] #162
- [x] #167 
- [x] #172
- [x] Clean up code layout
- [x] ~~DB migrations for MongoDB (check Beanie's docs)~~ (This can be only used on replica sets, which Kumiko does not use)
- [x] Remove unused coroutines for eco package

**Comment by No767** [comment]
oops made a mistake. should be #160 not #159

**Comment by No767** [comment]
still in the process of fixing up bugs
