### ISSUE TITLE
[Task] Migrate from SQLAlchemy ORM to Tortoise ORM

### ISSUE THREAD

**Issue by No767** [No767/Kumiko#193]
### Task Description

There is a reason behind this move. Writing out a ton of methods for SQLAlchemy ORM for Kumiko takes way too long and isn't as easy to build. So the idea is to use something like Tortoise ORM. Much faster, and meant for asyncio. SQLAlchemy ORM async is basically a shoehorned version of their sync version, but instead just using their async sessionmaker instead. SQLAlchemy ORM is way way too slow for Kumiko now, so the most logical decision is to go to Tortoise ORM

### Modules to migrate
- [x] Genshin Wish Sim
- [x] Eco User 
- [x] Eco User Inv
- [x] Eco Quests
- [x] Admin Logs
- [x] Marketplace (from MongoDB)
### Modules to Add
- [x] Server Profile / Config 

### Models Created
- [x] Genshin Wish Sim
- [x] Eco Marketplace
- [x] Eco Auction House
- [x] Eco User
- [x] Eco User Inv
- [x] Eco Quests
- [x] Admin Logs

**Comment by No767** [comment]
also don't forget to add caching. Coredis needs to be installed, and cache them via HSET, not SET

**Comment by No767** [comment]
Also add async decorators for caching

**Comment by No767** [comment]
Migrating from Tortoise ORM now to Prisma ORM
