### ISSUE TITLE
[Task] General cleanup

### ISSUE THREAD

**Issue by No767** [No767/Kumiko#260]
### Task Description

There are a bunch of stuff that needs to be addressed, and remade

- [x] Dropping Admin Logs (one day, this will be merged into the general logging system)
- [x] Moving from Tortoise ORM to Prisma. Tortorise ORM basically isn't being maintained and is considered stale (the other issue is that Tortoise ORM's pydantic models feature is quite honestly annoying to work with). Instead, the Prisma client for Python, which is now being used on Akari, works very well. That project has a really nice migration tool built in
- [x] Consider switching from Pycord back into discord.py v2. [Pycord V3 is already under the works](https://github.com/Pycord-Development/pycord-v3/discussions/128), and if released, means that Kumiko will have to migrate to Pycord V3. Might as well migrate to discord.py instead.  
- [x] Switching back from Coredis to redis-py. Mainly need it for RedisJSON support
- [x] Possible migration from GitHub projects to ClickUp or Monday.com
