### ISSUE TITLE
[Task] v0.6.x Roadmap

### ISSUE THREAD

**Issue by No767** [No767/Kumiko#269]
### Goals

- Only make the utils for the eco system
- Only make some of the complex logic for the eco system (eg the purchasing system)
- Migrate the codebase off to dpy 

Current roadmap and tasks that need to be done

- [x] Development of nova-mq
- [x] Migrate user profiles, user inv, marketplace, and quests to Prisma
- [x] Async decorator for caching (rebuild the caching lib)
- [x] Implement unit tests for caching lib 
- [x] Consolidate Rin's cogs into one category. So for example, the reddit cog can be converted into a cog that just has one of the commands, and that new cog w/ the new category has all of those
- [x] Sync mem cache implementation
