### ISSUE TITLE
[Task] Moderation V2

### ISSUE THREAD

**Issue by No767** [No767/Kumiko#292]
### Task Description

The moderation system should be brought back but needs to be heavily improved. Here's just some of the stuff that needs to be done:

- [x] Reintegrate old admin commands to the moderation system
- [ ] Warn command
- [x] ~~Reparse time strs using the R. Danny method~~ (now using a better lib for that)
- [ ] Admin UI for managing actions (eg warns, kicks, bans, etc)
- [x] ~~Case management system~~ (samet thing w/ modmail, not interested in moderating that)
- [x] ~~ModMail / User reporting system~~ (not interested in moderating that)

**Comment by No767** [comment]
This is being closed as ban/kick etc moderation commands are being phased out of Kumiko
