### ISSUE TITLE
[Task] Custom Prefixes

### ISSUE THREAD

**Issue by No767** [No767/Kumiko#366]
### Task Description

As of writing this, the custom prefixes module is almost done. There is some remaining work that needs to be done, and they are all documented here:

- [x] Finish and correctly validate the new prefix given (look into [`commands.Converter`](https://discordpy.readthedocs.io/en/stable/ext/commands/api.html?#discord.ext.commands.Converter))
- [x] ~~Set all of the command replies to be ephemeral (except the info cmd)~~ (there is no need for this)
- [x] ~~Implement further checks for DM contexts~~ (There is no need to do so since all of the commands are guild only, and the default prefix is returned if it is in a DM context
- [x] Implement a proper error embed for `ValidationError` exceptions
- [x] ~~Consider using upserts instead (aka `ON CONFLICT DO UPDATE...`)~~ (As of writing this (7/8/2023), this is not needed. When the guild is removed, then it is guaranteed that the rows associated with the server (including the logging config) will be deleted. So when the guild gets rejoined, all we need to do is to insert the data again. Upon testing, a new row for the logging config is created instead. This has to do with the constraints on the schema instead. Unless there are issues later down the road, I don't see this as important to implement)
