### ISSUE TITLE
[Task] Custom Logging

### ISSUE THREAD

**Issue by No767** [No767/Kumiko#368]
### Task Description

The custom logging module (EventsLog) only contains three main loggers as of now - member events (joins/leaves), mod events (bans, kicks, etc), and eco events (later to be implemented, but plans to add for who bought what, etc). Later will be added in the future. In order to complete the EventsLog module, the following tasks needs to be completed:

- [x] Implement listeners for the events
- [x] Add the events config
- [x] Polish up the code and test

**Comment by No767** [comment]
finished
