### ISSUE TITLE
[Task] The Cleanup Before Production

### ISSUE THREAD

**Issue by No767** [No767/Kumiko#445]
### Task Description

At this rate, v0.12.0-alpha is *almost* stable, but there needs to be some cleanup work that would be done before.

- [x] Remove any dead code (eg the dead code in the cache lib)
- [x] Move `JapaneseDictEntry` and `EnglishDictEntry` to msgspec (last part to move to msgspec)
- [x] Draft up an essay for why `message_content` is needed (the DNd system will be perfect)
- [x] Calculate all perms needed and make a oauth2 url for kumiko
- [x] Implement Blacklisting system from Catherine-Chan
- [x] Interaction Checks on all views
- [x] Config loader from Catherine-Chan
- [x] discord-ext-ipcx IPC layer w/ healthcheck
- [x] Clean up Redirects moderation system
- [x] Massive upgrades to the GitHub cog, new issues system
- [x] Cleaning up the search cog
### Ideas and Feats

- [x] #460
