### ISSUE TITLE
[Task] Python 3.12 Support

### ISSUE THREAD

**Issue by No767** [No767/Kumiko#469]
### Task Description

Breaking protocol from what is written on the documentation, Python 3.12 does not offer many substantial changes, so I'll greenlight the operation to upgrade to Python 3.12. But there are many that should be noted before the upgrade can happen:

For some libs, they need to be built from source. So here are the major packages needed:

- gcc
- libsystemd-dev

And waiting on wheels:

- hiredis-py
- cysystemd

These libraries are blocking the potential release of 3.12 support:

- [x] discord.py (Confirmed by Greg that there are not much major changes, but waiting on these issues to be resolved below)
    - ~~https://github.com/nodejs/llhttp/issues/249~~ (Regression tests released under llhttp v9.1.3)
    - ~~https://github.com/aio-libs/aiohttp/issues/7639~~ (Resolved)
    - https://github.com/aio-libs/aiohttp/issues/7675 (Keep an eye for this one)
- [x] Msgspec (v0.18.3 releases 3.12 support)
- [x] Orjson
- [x] asyncpg (master, https://github.com/MagicStack/asyncpg/commit/deea86cebf69a2b489d5e0bfa8ba5b5a562b5839 / v.29.0)
- [x] Brolti (can remove if doesn't support 3.12 in time)
- [x] uvloop (master / v0.18.0, https://github.com/MagicStack/uvloop/commit/9f82bd74447aa34abb6fa1b34d1d011d027c4369)
- [x] redis (Redis-py itself is fine, Hiredis needs to be built from source)
- [x] ~~ciso8601~~ (Replace with stdlib implementation + polyfill `backports.datetime_fromisoformat` for pre-3.11)
- [x] cysystemd (Needs to be built from source w/ GCC)
- [x] winloop
- [x] lru-dict (If they don't build wheels for this, since this package is just one C file, just build that from source using GCC)

**Comment by No767** [comment]
multidict is the last one, but i'm already tracking that one
