### ISSUE TITLE
[Task] Cleaning up the codebase

### ISSUE THREAD

**Issue by No767** [No767/Kumiko#505]
### Task Description

Kumiko's codebase is pretty huge and is in the process of being reworked. 

## Need to have / Currently working on

- [x] Webhook manager and Webhook-based EventsLog
- [x] Condensed migrations and schema
- [ ] Rebuild parts (user inv, marketplace, job management) of the economy system
- [x] Pins redesign
- [ ] Clean up and redo the dict commands

## Nice to have
- [x] Redo the pride profile to only allow identities from a pre-compiled list

**Comment by No767** [comment]
New goal, new future
