### ISSUE TITLE
[Task] Jobs System

### ISSUE THREAD

**Issue by No767** [No767/Kumiko#83]
### Task Description

Would be nice to have a jobs system. This jobs system is really what sets Kumiko apart from most multipurpose bots with an economy. Especially on how the ranks system works.

Moving forwards with the implementation, here are some ideas to be considered:

- Each job gives you a base pay + bonus (to be added later). The amount of money you have determines your current rank. The algo will be an exponential function. For example, I have an job that earns me 50 petals per hour (just like US jobs), and my rank is 1. Over time, I get more petals, (50, then 50 more, and so forth) and once I reach to an certain amount of petals (say 2500 for example), then my rank goes up. This essentially ties both the rank and jobs system together
- Once you reach a certain rank, you unlock features, such as bounties, (aka quests, aka tasks), and more
- The higher the rank, the better the jobs are
- Include a default set of jobs?

And here is the general checklist:

- [x] Add CRUD commands
- [x] Add list/unlist job commands
- [x] Add purge command
- [x] ~~Add transfer (ownership) command~~ (It just doesn't make sense to "transfer" a job away, when in reality, you kinda have to apply/quit for one instead)
- [x] Add remove by id command
- [x] Add an application system. Aka apply/quit commands. the max amount of jobs that one user can have is 3
- [x] Add the actual task running in the background that updates them as needed.

**Comment by No767** [comment]
Sorry Edelweiss, but I'm going to rip off some of your ideas
- Bank system (w/ Checking and savings. Just like how an actual bank works in the US)
- Job, with salary
- Credit Card
- Personal Wallet + Debt + Premium

**Comment by No767** [comment]
This jobs feature is finally done. After being considered for so long, it has finally been implemented
